### ISSUE TITLE
Add Testing

### ISSUE THREAD

**Issue by kareemmahlees** [the-sabra/express-tool#6]
P.S: This was Intentionally gonna be in this pr #5 

As for now, there are no tests to automatically run and see if the application is working.
A possible solution is using [Vitest](https://vitest.dev/) as a test suite to run tests against the whole application.

If this is acceptable you can assign this to me and I will create a pull request for this.

**Comment by thesabrah** [comment]
I hate `testing`, I know it's important, but okay I want to learn from you about how you are testing this project.
